indicator(title="Directional Movement Index", shorttitle="DMI", format=format.price, precision=4, timeframe="", timeframe_gaps=true)
lensig = input.int(14, title="ADX Smoothing", minval=1, maxval=50)
len = input.int(14, minval=1, title="DI Length")
up = ta.change(high)
down = -ta.change(low)
plusDM = na(up) ? na : (up > down and up > 0 ? up : 0)
minusDM = na(down) ? na : (down > up and down > 0 ? down : 0)
trur = ta.rma(ta.tr, len)
plus = fixnan(100 * ta.rma(plusDM, len) / trur)
minus = fixnan(100 * ta.rma(minusDM, len) / trur)
sum = plus + minus
adx = 100 * ta.rma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), lensig)
plot(adx, color=#ff8533, title="ADX", linewidth=2)
plot(plus, color=#00ff00, title="+DI")
plot(minus, color=#ff1a1a, title="-DI")

//add horizontal line => threshold
weakTrendTH = hline(25, title="1st Threshold", color=color.gray, linestyle=hline.style_dashed)
veryWeakTrendTH = hline(20, title="2nd Threshold", color=color.gray, linestyle=hline.style_dashed)
